name: CheckLinks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checklinks:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check links
        run: |
          sudo chmod 777 .
          make check-links
